version: '3'

services:
  orders-app-postgres:
    image: postgres
    env_file:
      - .env
    container_name: ${POSTGRES_DB}
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - orders-app-network

networks:
  orders-app-network:
    driver: bridge
